# Fly.io configuration
# File: fly.toml

app = "elephas-ai"
primary_region = "dfw"

[build]

[env]
  ENVIRONMENT = "production"
  MODEL_PATH = "elephasai/elephas"
  LOG_LEVEL = "INFO"
  PORT = "8000"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[deploy]
  release_command = "python -c 'print(\"🚀 Elephas AI deploying...\")'"

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 8000
    timeout = "10s"
