services:
  - type: web
    name: elephas-ai-api
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    domains:
      - elephas-ai-api.onrender.com
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MODEL_PATH
        value: elephasai/elephas  # Your private model
      - key: HF_TOKEN
        sync: false  # Set this manually in Render dashboard for security
      - key: LOG_LEVEL
        value: INFO
      - key: API_TITLE
        value: Elephas AI Security API
      - key: API_VERSION
        value: v2.0
      - key: API_DESCRIPTION
        value: Advanced AI-powered threat detection and security analysis
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: "8000"
      # Memory optimization environment variables for free tier
      - key: TRANSFORMERS_CACHE
        value: /tmp/transformers_cache
      - key: TORCH_HOME
        value: /tmp/torch
      - key: HF_HOME
        value: /tmp/huggingface
      - key: OMP_NUM_THREADS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
    disk:
      name: elephas-ai-disk
      mountPath: /opt/render/project/data
      sizeGB: 1
