services:
  - type: web
    name: elephas-ai-api
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    domains:
      - elephas-ai-api.onrender.com
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: MODEL_PATH
        value: unitary/toxic-bert  # Free public model - no HF_TOKEN needed
      # Comment out HF_TOKEN for free deployment
      # - key: HF_TOKEN
      #   sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: API_TITLE
        value: Elephas AI Security API
      - key: API_VERSION
        value: v2.0
      - key: API_DESCRIPTION
        value: Advanced AI-powered threat detection and security analysis
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PORT
        value: "8000"
    disk:
      name: elephas-ai-disk
      mountPath: /opt/render/project/data
      sizeGB: 1
